### ISSUE TITLE
Ch01 - az aks create ver k8s 1.18.8  not in eastus

### ISSUE THREAD

**Issue by Grant-Steinfeld** [sixeyed/kiamol#6]
in kiamol softcover book 2021 ,  on page 12

1.3.5 Run a single-node Kubernetes clusterin Azure

 in stanza starting with _az aks create_  ... --kubernetes-version 1.18.8  

has an error that ver 1.18.8 is not available in location eastus

a possible solution was to use the closest  k8s version  1.18.14

**Comment by sixeyed** [comment]
Thanks Grant - as new Kubernetes versions are supported in AKS, older versions get deprecated. 

For reference, this is how to check the supported versions in a region:

```
az aks get-versions --location eastus -o table
```

I'll update the notes in the ch01 folder.
